/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalendarIndexRouteImport } from './routes/calendar/index'
import { Route as CalendarUserRouteImport } from './routes/calendar/$user'
import { Route as AuthUpdatePasswordRouteImport } from './routes/auth/update-password'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarIndexRoute = CalendarIndexRouteImport.update({
  id: '/calendar/',
  path: '/calendar/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarUserRoute = CalendarUserRouteImport.update({
  id: '/calendar/$user',
  path: '/calendar/$user',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthUpdatePasswordRoute = AuthUpdatePasswordRouteImport.update({
  id: '/auth/update-password',
  path: '/auth/update-password',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/update-password': typeof AuthUpdatePasswordRoute
  '/calendar/$user': typeof CalendarUserRoute
  '/calendar/': typeof CalendarIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/update-password': typeof AuthUpdatePasswordRoute
  '/calendar/$user': typeof CalendarUserRoute
  '/calendar': typeof CalendarIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/update-password': typeof AuthUpdatePasswordRoute
  '/calendar/$user': typeof CalendarUserRoute
  '/calendar/': typeof CalendarIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth/update-password' | '/calendar/$user' | '/calendar/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth/update-password' | '/calendar/$user' | '/calendar'
  id:
    | '__root__'
    | '/'
    | '/auth/update-password'
    | '/calendar/$user'
    | '/calendar/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthUpdatePasswordRoute: typeof AuthUpdatePasswordRoute
  CalendarUserRoute: typeof CalendarUserRoute
  CalendarIndexRoute: typeof CalendarIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar/': {
      id: '/calendar/'
      path: '/calendar'
      fullPath: '/calendar/'
      preLoaderRoute: typeof CalendarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar/$user': {
      id: '/calendar/$user'
      path: '/calendar/$user'
      fullPath: '/calendar/$user'
      preLoaderRoute: typeof CalendarUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/update-password': {
      id: '/auth/update-password'
      path: '/auth/update-password'
      fullPath: '/auth/update-password'
      preLoaderRoute: typeof AuthUpdatePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthUpdatePasswordRoute: AuthUpdatePasswordRoute,
  CalendarUserRoute: CalendarUserRoute,
  CalendarIndexRoute: CalendarIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
